title: "Data Science Portfolio"
description: "Portfolio"
url: "https://anneliset47.github.io"
baseurl: ""  # for user/username.github.io sites

# Favicon
favicon: /assets/images/projects.png

# use Minimal Mistakes via GitHub Pages
remote_theme: "mmistakes/minimal-mistakes"

# pick a skin (others: air, aqua, contrast, dark, dirt, neon, sunrise)
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# navigation & author
collections:
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      show_date: false     # hides date/updated meta
      read_time: false
      share: false
      related: false

author: Annelise Thorn

search: true
breadcrumbs: true

# hide the RSS/Atom link
atom_feed:
  hide: true

# no footer links at all
footer:
  links: []

# remove the copyright line (leave it empty)
copyright: ""


